import 'helper.dart';

class GrammarQuestionBank {
  final List<Map<String, dynamic>> _A1 = [
    {'phrase': 'I like to eat apples.', 'isCorrect': true},
    {'phrase': 'She has a small dog.', 'isCorrect': true},
    {'phrase': 'They play soccer in the park.', 'isCorrect': true},
    {'phrase': 'The sun is shining brightly.', 'isCorrect': true},
    {'phrase': 'He drinks water every day.', 'isCorrect': true},
    {'phrase': 'We go to school by bus.', 'isCorrect': true},
    {'phrase': 'I see a bird in the tree.', 'isCorrect': true},
    {'phrase': 'She reads a book in the afternoon.', 'isCorrect': true},
    {'phrase': 'The cat is sleeping on the couch.', 'isCorrect': true},
    {'phrase': 'He likes to draw pictures.', 'isCorrect': true},
    {'phrase': 'They are friends at school.', 'isCorrect': true},
    {'phrase': 'I have a brother and a sister.', 'isCorrect': true},
    {'phrase': 'The flowers are beautiful in spring.', 'isCorrect': true},
    {'phrase': 'She sings very well.', 'isCorrect': true},
    {'phrase': 'We watch TV in the evening.', 'isCorrect': true},
    {'phrase': 'I ride my bike to the store.', 'isCorrect': true},
    {'phrase': 'He plays video games on weekends.', 'isCorrect': true},
    {'phrase': 'The baby is laughing happily.', 'isCorrect': true},
    {'phrase': "They eat dinner at six o'clock.", 'isCorrect': true},
    {'phrase': 'I take a shower in the morning.', 'isCorrect': true},
    {'phrase': 'She writes in her notebook.', 'isCorrect': true},
    {'phrase': 'The coffee is hot and tasty.', 'isCorrect': true},
    {'phrase': 'We love to go to the beach.', 'isCorrect': true},
    {'phrase': 'He works in a big office.', 'isCorrect': true},
    {'phrase': 'I enjoy listening to music.', 'isCorrect': true},
    {'phrase': 'The dog runs fastly in park.', 'isCorrect': false},
    {'phrase': 'She has three cat at home.', 'isCorrect': false},
    {'phrase': 'I am going to shopping tomorrow.', 'isCorrect': false},
    {'phrase': 'He play soccer every week.', 'isCorrect': false},
    {'phrase': 'They was happy to see the movie.', 'isCorrect': false},
    {'phrase': 'The book is on the table’s.', 'isCorrect': false},
    {'phrase': 'She don’t like bananas.', 'isCorrect': false},
    {'phrase': 'I can swim very good.', 'isCorrect': false},
    {'phrase': 'The children is playing outside.', 'isCorrect': false},
    {'phrase': "He eat lunch at twelve o'clock.", 'isCorrect': false},
    {'phrase': 'She walk to school every days.', 'isCorrect': false},
    {'phrase': 'The stars shines in the night sky.', 'isCorrect': false},
    {'phrase': 'We is going to the party tonight.', 'isCorrect': false},
    {'phrase': 'I have many friends in school.', 'isCorrect': false},
    {'phrase': 'The teacher ask a question.', 'isCorrect': false},
    {'phrase': 'She watches TV every night.', 'isCorrect': false},
    {'phrase': 'He likes play guitar.', 'isCorrect': false},
    {'phrase': 'They are eat pizza for dinner.', 'isCorrect': false},
    {'phrase': 'The cat chases the mice’s.', 'isCorrect': false},
    {'phrase': 'I enjoy to dance at parties.', 'isCorrect': false},
    {'phrase': 'The weather are nice today.', 'isCorrect': false},
    {'phrase': 'She reads book in the evening.', 'isCorrect': false},
    {'phrase': 'He goes to gym every morning.', 'isCorrect': false},
    {'phrase': 'We likes to play games.', 'isCorrect': false},
    {'phrase': 'The phone ring loudly in the room.', 'isCorrect': false},
  ];

  final List<Map<String, dynamic>> _A2 = [
    {'phrase': 'I want to learn how to play the guitar.', 'isCorrect': true},
    {'phrase': 'She goes to the gym every day after work.', 'isCorrect': true},
    {'phrase': 'They are planning a trip to Spain next summer.', 'isCorrect': true},
    {'phrase': 'The children are playing in the backyard.', 'isCorrect': true},
    {'phrase': 'He usually eats breakfast at seven o’clock.', 'isCorrect': true},
    {'phrase': 'We enjoy watching movies together on weekends.', 'isCorrect': true},
    {'phrase': 'I often visit my grandparents on holidays.', 'isCorrect': true},
    {'phrase': 'She is studying for her exams this week.', 'isCorrect': true},
    {'phrase': 'The weather is getting colder as winter approaches.', 'isCorrect': true},
    {'phrase': 'He likes to read books about history.', 'isCorrect': true},
    {'phrase': 'We are having a party at our house next Saturday.', 'isCorrect': true},
    {'phrase': 'I bought a new dress for the special occasion.', 'isCorrect': true},
    {'phrase': 'She speaks three languages fluently.', 'isCorrect': true},
    {'phrase': 'They like to go hiking in the mountains.', 'isCorrect': true},
    {'phrase': 'I am learning how to cook Italian food.', 'isCorrect': true},
    {'phrase': 'The flowers in the garden smell very nice.', 'isCorrect': true},
    {'phrase': 'He takes the bus to school every morning.', 'isCorrect': true},
    {'phrase': 'We are excited to see our friends this weekend.', 'isCorrect': true},
    {'phrase': 'I often go for a walk in the evening.', 'isCorrect': true},
    {'phrase': 'She has a collection of stamps from different countries.', 'isCorrect': true},
    {'phrase': 'The cake tastes delicious and looks beautiful.', 'isCorrect': true},
    {'phrase': 'They play chess together every Friday.', 'isCorrect': true},
    {'phrase': 'I need to buy groceries for the week.', 'isCorrect': true},
    {'phrase': 'She enjoys taking photos of nature.', 'isCorrect': true},
    {'phrase': 'We always celebrate our birthdays with cake and friends.', 'isCorrect': true},
    {'phrase': 'I wants to learn how to ride bicycle.', 'isCorrect': false},
    {'phrase': 'She go to work every day at eight.', 'isCorrect': false},
    {'phrase': 'They are planning a picnic in the park next weekend.', 'isCorrect': false},
    {'phrase': 'The students studies for their test tomorrow.', 'isCorrect': false},
    {'phrase': 'He often forget his keys at home.', 'isCorrect': false},
    {'phrase': 'We enjoys playing soccer every Saturday.', 'isCorrect': false},
    {'phrase': 'I visited my aunt on last weekend.', 'isCorrect': false},
    {'phrase': 'She reading a book about science now.', 'isCorrect': false},
    {'phrase': 'The sun shine bright in the sky today.', 'isCorrect': false},
    {'phrase': 'He like to watch series on TV.', 'isCorrect': false},
    {'phrase': 'We are making cookies for our friends tomorrow.', 'isCorrect': false},
    {'phrase': 'I seen a great movie last night.', 'isCorrect': false},
    {'phrase': 'She speaks English very good.', 'isCorrect': false},
    {'phrase': 'They likes to play video games after school.', 'isCorrect': false},
    {'phrase': 'I am going to the store buy some milk.', 'isCorrect': false},
    {'phrase': 'The dogs are barking loudly at the strangers.', 'isCorrect': false},
    {'phrase': 'He take his lunch to school every day.', 'isCorrect': false},
    {'phrase': 'We happy to see you at the party.', 'isCorrect': false},
    {'phrase': 'I goes jogging in the morning every day.', 'isCorrect': false},
    {'phrase': 'She has many friend in her class.', 'isCorrect': false},
    {'phrase': 'The soup taste very delicious and hot.', 'isCorrect': false},
    {'phrase': 'They play basketball at the court every week.', 'isCorrect': false},
    {'phrase': 'I need to clean my room today.', 'isCorrect': false},
    {'phrase': 'She enjoys dance to her favorite music.', 'isCorrect': false},
    {'phrase': 'We will celebrate his birthday with a cake.', 'isCorrect': false},
  ];

  final List<Map<String, dynamic>> _B1 = [
    {'phrase': 'I have been living in this city for three years.', 'isCorrect': true},
    {'phrase': 'She used to play the piano when she was younger.', 'isCorrect': true},
    {'phrase': 'The manager will meet with the team tomorrow.', 'isCorrect': true},
    {'phrase': 'They are considering moving to another country.', 'isCorrect': true},
    {'phrase': 'He has already finished his homework before dinner.', 'isCorrect': true},
    {'phrase': 'We usually go for a walk in the park on Sundays.', 'isCorrect': true},
    {'phrase': 'The book that you lent me is very interesting.', 'isCorrect': true},
    {'phrase': 'She has just arrived at the airport.', 'isCorrect': true},
    {'phrase': 'I need to finish the report by Friday.', 'isCorrect': true},
    {'phrase': 'The concert was canceled due to the rain.', 'isCorrect': true},
    {'phrase': 'He didn’t knew about the meeting.', 'isCorrect': false},
    {'phrase': 'We will going to the movies tonight.', 'isCorrect': false},
    {'phrase': 'She don’t likes coffee.', 'isCorrect': false},
    {'phrase': 'They are speak with their teacher now.', 'isCorrect': false},
    {'phrase': 'He has ate dinner already.', 'isCorrect': false},
    {'phrase': 'The car was being wash at the time.', 'isCorrect': false},
    {'phrase': 'We should of gone earlier.', 'isCorrect': false},
    {'phrase': 'She enjoy reading books about history.', 'isCorrect': false},
    {'phrase': 'I have finish my work for today.', 'isCorrect': false},
    {'phrase': 'He take the bus to work every day.', 'isCorrect': false},
  ];

  final List<Map<String, dynamic>> _B2 = [
    {'phrase': 'The book I read recently was fascinating.', 'isCorrect': true},
    {'phrase': 'She managed to solve the problem quickly.', 'isCorrect': true},
    {'phrase': 'They have been working here since 2015.', 'isCorrect': true},
    {'phrase': 'We are looking forward to your visit.', 'isCorrect': true},
    {'phrase': 'He was promoted after only a few months.', 'isCorrect': true},
    {'phrase': 'The teacher suggested that we review the material.', 'isCorrect': true},
    {'phrase': 'I wouldn’t have gone if I had known.', 'isCorrect': true},
    {'phrase': 'She is well known for her acting skills.', 'isCorrect': true},
    {'phrase': 'He will have completed the project by next week.', 'isCorrect': true},
    {'phrase': 'They will not come to the meeting unless it is urgent.', 'isCorrect': true},
    {'phrase': 'He didn’t need came to the meeting.', 'isCorrect': false},
    {'phrase': 'We should not have been go there.', 'isCorrect': false},
    {'phrase': 'She would had come if she knew.', 'isCorrect': false},
    {'phrase': 'They was planning to leave early.', 'isCorrect': false},
    {'phrase': 'I will finished the report tomorrow.', 'isCorrect': false},
    {'phrase': 'The book is been read by the students.', 'isCorrect': false},
    {'phrase': 'She must to complete the assignment today.', 'isCorrect': false},
    {'phrase': 'We look forward to meet you.', 'isCorrect': false},
    {'phrase': 'He have been waiting for an hour.', 'isCorrect': false},
    {'phrase': 'They doesn’t know what to do.', 'isCorrect': false},
  ];

  final List<Map<String, dynamic>> _C1 = [
    // Correct
    {'phrase': 'Despite the rain, we decided to go for a hike.', 'isCorrect': true},
    {'phrase': 'He suggested that I try the new restaurant in town.', 'isCorrect': true},
    {'phrase': 'The committee has reached a consensus on the proposal.', 'isCorrect': true},
    {'phrase': 'I look forward to meeting you at the conference next week.', 'isCorrect': true},
    {'phrase': 'She is very good at solving complex problems.', 'isCorrect': true},
    {'phrase': 'If I had known about the event, I would have attended.', 'isCorrect': true},
    {'phrase': 'They argued that the policy was not only ineffective but also unfair.', 'isCorrect': true},
    {'phrase': 'The manager, along with her team, is presenting their findings.', 'isCorrect': true},
    {'phrase': 'I am used to driving on the left side of the road.', 'isCorrect': true},
    {'phrase': 'There are several ways to approach this issue effectively.', 'isCorrect': true},
    {'phrase': 'He said that he would help me with the project, but he never did.', 'isCorrect': true},
    {'phrase': 'The results of the experiment were inconclusive.', 'isCorrect': true},
    {'phrase': 'It is essential that every student understands the requirements.', 'isCorrect': true},
    {'phrase': 'I can’t help but feel that something is off.', 'isCorrect': true},
    {'phrase': 'She has less time to complete her assignments this semester.', 'isCorrect': true},
    {'phrase': 'The novel, which was published in the 1920s, remains popular today.', 'isCorrect': true},
    {'phrase': 'He didn’t have enough money to buy the concert tickets.', 'isCorrect': true},
    {'phrase': 'It is important to consider all perspectives.', 'isCorrect': true},
    {'phrase': 'They were planning to launch the product by the end of the year.', 'isCorrect': true},
    {'phrase': 'This theory is based on the assumption that all humans behave rationally.', 'isCorrect': true},
    {'phrase': 'I would rather you didn’t share this information with anyone.', 'isCorrect': true},
    {'phrase': 'The team has been working tirelessly to meet the deadline.', 'isCorrect': true},
    {'phrase': 'He is one of those people who always seem to be late.', 'isCorrect': true},
    {'phrase': 'She has been studying English for five years, but still makes mistakes.', 'isCorrect': true},
    {'phrase': 'The company has grown significantly in the last decade.', 'isCorrect': true},

    // Incorrect
    {'phrase': 'She has wrote an impressive article about climate change.', 'isCorrect': false},
    {'phrase': 'Despite of the rain, we decided to go for a hike.', 'isCorrect': false},
    {'phrase': 'He suggested me to try the new restaurant in town.', 'isCorrect': false},
    {'phrase': 'The committee have reached a consensus on the proposal.', 'isCorrect': false},
    {'phrase': 'I look forward to meet you at the conference next week.', 'isCorrect': false},
    {'phrase': 'She is very good in solving complex problems.', 'isCorrect': false},
    {'phrase': 'If I would have known about the event, I would have attended.', 'isCorrect': false},
    {'phrase': 'The manager, along with her team, are presenting their findings.', 'isCorrect': false},
    {'phrase': 'I am used to drive on the left side of the road.', 'isCorrect': false},
    {'phrase': 'There is several ways to approach this issue effectively.', 'isCorrect': false},
    {'phrase': 'The results of the experiment was inconclusive.', 'isCorrect': false},
    {'phrase': 'It is essential that every student understand the requirements.', 'isCorrect': false},
    {'phrase': 'I can’t help but to feel that something is off.', 'isCorrect': false},
    {'phrase': 'The novel, which was published in 1U20s, remains popular today.', 'isCorrect': false},
    {'phrase': 'He didn’t have enough money for to buy the concert tickets.', 'isCorrect': false},
    {'phrase': 'It is important to take into consideration all perspectives.', 'isCorrect': false},
    {'phrase': 'They was planning to launch the product by the end of the year.', 'isCorrect': false},
    {'phrase': 'The team have been working tirelessly to meet the deadline.', 'isCorrect': false},
    {'phrase': 'He is one of those people who always seems to be late.', 'isCorrect': false},
    {'phrase': 'She have been studying English for five years, but still makes mistakes.', 'isCorrect': false},
    {'phrase': 'He didn’t have no money left.', 'isCorrect': false},
    {'phrase': 'The proposal was not only unnecessary but also redundant.', 'isCorrect': false},
    {'phrase': 'I would rather that you don’t share this information.', 'isCorrect': false},
    {'phrase': 'It’s a topic what I find very interesting.', 'isCorrect': false},
    {'phrase': 'She don’t like the new schedule.', 'isCorrect': false},
  ];

  final List<Map<String, dynamic>> _C2 = [
    // Correct
    {'phrase': 'The new policy, which aims to reduce carbon emissions, has garnered widespread support.', 'isCorrect': true},
    {'phrase': 'Having worked in the field for over a decade, she possesses a wealth of knowledge.', 'isCorrect': true},
    {'phrase': 'It is imperative that we address the underlying issues before implementing any changes.', 'isCorrect': true},
    {'phrase': 'Despite the challenges they faced, the team completed the project ahead of schedule.', 'isCorrect': true},
    {'phrase': 'He expressed a desire to further his studies abroad to enhance his career prospects.', 'isCorrect': true},
    {'phrase': 'The research findings, although preliminary, indicate a significant correlation.', 'isCorrect': true},
    {'phrase': 'She has consistently demonstrated her ability to think critically.', 'isCorrect': true},
    {'phrase': 'The organization seeks to empower individuals through education.', 'isCorrect': true},
    {'phrase': 'I have always believed that open communication is crucial for collaboration.', 'isCorrect': true},
    {'phrase': 'The seminar, which featured esteemed speakers, provided valuable insights.', 'isCorrect': true},
    {'phrase': 'He often reflects on his experiences, recognizing how they shaped his growth.', 'isCorrect': true},
    {'phrase': 'It is essential for leaders to cultivate an inclusive environment.', 'isCorrect': true},
    {'phrase': 'The documentary highlights the impact of climate change on vulnerable populations.', 'isCorrect': true},
    {'phrase': 'They devised a strategy that met the objectives and exceeded expectations.', 'isCorrect': true},
    {'phrase': 'The initiative aims to foster innovation by encouraging collaboration.', 'isCorrect': true},
    {'phrase': 'She remains committed to her goal of improving literacy rates.', 'isCorrect': true},
    {'phrase': 'The novel explores themes of identity and resonates with readers.', 'isCorrect': true},
    {'phrase': 'He was able to articulate his ideas clearly, impressing the audience.', 'isCorrect': true},
    {'phrase': 'The workshop provided participants with skills applicable in real-world scenarios.', 'isCorrect': true},
    {'phrase': 'It is widely acknowledged that mental health is crucial for well-being.', 'isCorrect': true},
    {'phrase': 'The study challenges conventional wisdom and invites further investigation.', 'isCorrect': true},
    {'phrase': 'She has taken on additional responsibilities, demonstrating commitment.', 'isCorrect': true},
    {'phrase': 'The conference will address pressing global issues and promote dialogue.', 'isCorrect': true},
    {'phrase': 'Their collaborative efforts resulted in a comprehensive report.', 'isCorrect': true},
    {'phrase': 'The research, despite its limitations, offers valuable insights.', 'isCorrect': true},

    // Incorrect
    {'phrase': 'Having completed the report, the manager asked for it to be reviewed.', 'isCorrect': false},
    {'phrase': 'Despite of numerous attempts, the issue persisted unresolved.', 'isCorrect': false},
    {'phrase': 'He suggested that I should consider the position.', 'isCorrect': false},
    {'phrase': 'The committee have deliberated for weeks.', 'isCorrect': false},
    {'phrase': 'I look forward to discuss the project.', 'isCorrect': false},
    {'phrase': 'She is accustomed to manage her time.', 'isCorrect': false},
    {'phrase': 'If he would have known about the changes, he would be prepared.', 'isCorrect': false},
    {'phrase': 'The presentation, which included research, was praised.', 'isCorrect': false},
    {'phrase': 'I am used to work under pressure, which many find quite challenging. There exists several alternative solutions that could potentially resolve the problem.', 'isCorrect': false},
    {'phrase': 'He remarked that he would assist with the project, yet he failed to follow through.', 'isCorrect': false},
    {'phrase': 'The findings of the experiment were surprising, and it contradicted previous studies.', 'isCorrect': false},
    {'phrase': 'It is crucial that every participant understands the implications of their actions. ', 'isCorrect': false},
    {'phrase': "I can't help but feel that there might be underlying issues that remain unaddressed.", 'isCorrect': false},
    {'phrase': 'She has significantly less time than before to dedicate to her studies, which is concerning.', 'isCorrect': false},
    {'phrase': 'The article, which was published in an esteemed journal, has sparked considerable debate.', 'isCorrect': false},
    {'phrase': "He didn't have enough resources to effectively carry out the project, which led to its failure.", 'isCorrect': false},
    {'phrase': 'It is essential to take into consideration all perspectives when making a decision of this magnitude.', 'isCorrect': false},
    {'phrase': 'They were planning to launch the initiative last quarter, but it was postponed due to unforeseen circumstances.', 'isCorrect': false},
    {'phrase': 'This theory, based on the premise that individuals behave rationally, has been widely debated.', 'isCorrect': false},
    {'phrase': 'I would rather you not disclose this information to anyone else involved in the project.', 'isCorrect': false},
    {'phrase': 'The team have consistently demonstrated their ability to meet tight deadlines and produce quality work.', 'isCorrect': false},
    {'phrase': 'He is one of those individuals who appears to thrive under pressure, which is quite rare.', 'isCorrect': false},
    {'phrase': 'She has been studying English for several years; however, she still encounters difficulties with complex structures.', 'isCorrect': false},
  ];

  List<Map<String, dynamic>> getRandomQuestions({String? cefrLevel, int? count}) {
    List<Map<String, dynamic>> questionBank;

    switch (cefrLevel) {
      case 'A1':
        questionBank = _A1;
      case 'A2':
        questionBank = _A2;
      case 'B1':
        questionBank = _B1;
      case 'B2':
        questionBank = _B2;
      case 'C1':
        questionBank = _C1;
      default:
        questionBank = _A1;
    }

    List<int> questionIndexes = getRandomNumbers(max: questionBank.length, count: count!);
    List<Map<String, dynamic>> questions = [];

    for (int index in questionIndexes) {
      questions.add(questionBank[index]);
    }

    return questions;
  }

}
